# Udemy Course: Python A-Z
## Section 3: Fundamentals Of Python
### LIST
Python Programming A-Z™ 
© Kirill Eremenko
https://www.superdatascience.com
_

This notebook contains exercises from section 3 of the course
List: think of a horizontal bookshelf and the elements are books inside the bookshelf
List and array different
List are ordered sets of elements
Note: vectors (in R) are numerated from 1
In python, list numerations starts from 0
Phython can have mix of data type

In [8]:
MyFirstList = [3, 45, 56, 732]
type(MyFirstList)

list

In [9]:
12 = ["hello", 24, True, 55.3]

SyntaxError: can't assign to literal (<ipython-input-9-37556bbba293>, line 1)

In [5]:
12

12

In [10]:
13 = ['how are you?', 55, MyFirstList]

SyntaxError: can't assign to literal (<ipython-input-10-0f92a27cbacc>, line 1)

---

In [11]:
range(15) #Python 3 - this is the same as xrange() in Python2

range(0, 15)

In [12]:
list(range(15))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [15]:
x = [ 1,2,3,4,5,6,7]
x

[1, 2, 3, 4, 5, 6, 7]

In [16]:
y = list(range(8))
y

[0, 1, 2, 3, 4, 5, 6, 7]

In [18]:
z2 = list(range(100, 120)) # here you are specifying a range
z2

[100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119]

In [19]:
z3 = list(range(100, 120, 2)) # here you can specifying a step to list your range
z3

[100, 102, 104, 106, 108, 110, 112, 114, 116, 118]

---

In [20]:
### Using [] Brackets

#Recall lists:

In [27]:
w = [ 'a', 'b', 'c', 'd', 'e']
w[0]


'a'

In [26]:
w[1]

'b'

In [30]:
w[5] # out of range, recall taht list starts at 0 (not 1)

IndexError: list index out of range

In [31]:
w[4]

'e'

In [32]:
#0 1 2 3 4
#-5 -4 -3 -2 -1

w[-1] #different behavior to R

'e'

In [33]:
w[-3]

'c'

In [40]:
#overwrite values:
w
w[2] = 63
w

['a', 'b', 63, 'd', 'e']

In [41]:
#lygometry: measuring and learning what we don't know

---

In [42]:
### SLICING : ###
#Slicing: taking a subset of the list
#In python slciing from index 2:7 means all numbers from 2 to up to less than 7 (without including 7)

# -8:7 

#2:9:2 #here we want every second element
#start:finish:step

In [44]:
letters =['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']
letters

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

In [45]:
letters[ : ]

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

In [46]:
letters[:]

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

In [47]:
letters[2:]

['C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

In [48]:
letters[:7]

['A', 'B', 'C', 'D', 'E', 'F', 'G']

In [49]:
letters[2:7]

['C', 'D', 'E', 'F', 'G']

In [50]:
letters[-8:7]

['C', 'D', 'E', 'F', 'G']

In [51]:
letters[-8:-3]

['C', 'D', 'E', 'F', 'G']

In [52]:
#Advance Slicing

letters[2:9:2]

['C', 'E', 'G', 'I']

In [53]:
letters

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

In [54]:
letters[::3]

['A', 'D', 'G', 'J']

In [56]:
#consider specifying a negative step
letters[::-3] # interesting it reverses the list!

['J', 'G', 'D', 'A']

In [57]:
letters[2:7]

['C', 'D', 'E', 'F', 'G']

In [58]:
letters[2:7:1]

['C', 'D', 'E', 'F', 'G']

In [60]:
letters[2:7:-1] # you cannot get to 2:7 going backwards, so your index has to indicate that you are going backwards

[]

In [61]:
# so to correct this issue:
letters[6:1:-1]

['G', 'F', 'E', 'D', 'C']

In [62]:
letters[6:1:-2]

['G', 'E', 'C']

---

In [64]:
#TUPLES = immutable list
#you cannot change them

t1 = (345, 674, 934)
t1

(345, 674, 934)

In [65]:
t1[0]

345

In [66]:
t1[1]

674

In [67]:
t1[1] = 645 # you cannot change tuple # its more related to programming and development

TypeError: 'tuple' object does not support item assignment

---

### FUNCTIONS

Think of a function as a blender that blends fruits into smoothie
you put in an input into functions and they give you an output
below are some functions that have been used in the course so far:

In [69]:
#range
range(20, 31)

range(20, 31)

In [70]:
#list
list(range(20,31))

[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]

In [71]:
mylist1 = list(range(20,31)) # here we stored our list
mylist1

[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]

In [72]:
#print
print(mylist1)

[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]


In [73]:
#length 
#it counts the number of elements in your list
len(mylist1)

11

In [74]:
#type: it tells you the type of object
type(mylist1)


list

In [75]:
#min
min(mylist1)

20

In [77]:
#max
max(mylist1)

30

In [79]:
max(11, 435, 7)

435

---

#### Packages

Python programming is built to be lean so that you can use packages
what's in these packages: different functions (different blenders)

module: file with python definition
a package: collection of related modules
Below are the steps for adding packages:
1. Find package
2. Install package unto machine
3. Import Package/Function

Step1: Find package (option)
Source: Github: https://github.com/

Step2: Install package unto machine
you need a python distribution on your machine
windows: conda install packagename (in console) or pip install packagename
mac: open terminal -> conda install packagename or pip install packagename
if you are already running jupiter, you need to open another terminal: CMND + T

example, let's install  a package on web scraping

step1: Look for web scrapping: 


In [81]:
import scrapy

In [82]:
from scrapy.crawler import CrawlerProcess

In [83]:
import numpy

---

### NUMPY and ARRAYS IN PYTHON

In [118]:
#let's create a list of numbers
l = [23245, 27, 546, 215, -1234]
l

[23245, 27, 546, 215, -1234]

In [119]:
#Arrays:
#2 types: regular and numpy arrays

import numpy as np

In [120]:
np.array

<function numpy.core.multiarray.array>

In [121]:
a=np.array(l)
a

array([23245,    27,   546,   215, -1234])

In [122]:
#you cannot have an array of different data types
b = np.array([12, 455, 63.3, True, "abc"])
b

array(['12', '455', '63.3', 'True', 'abc'], dtype='<U32')

In [127]:
l.pop()

27

In [128]:
print(b)

['12' '455' '63.3' 'True' 'abc']


In [130]:
#there are data stored inside of the list (type 'tab' on your keyboard)
a.mean()

4559.8

---

### Slicing Arrays

A quick recap of slicing:

In [97]:
l[1:]

[27, 546, 215]

In [98]:
l[0:2]

[23245, 27]

In [99]:
l[::2]

[23245, 546]

In [100]:
#now let's look at our data
# when slicing an array, you don't create a copy of that array
#python does this to save space

a

array([23245,    27,   546,   215, -1234])

In [102]:
a[2:]

array([  546,   215, -1234])

In [101]:
a[2:4]

array([546, 215])

In [103]:
b

array(['12', '455', '63.3', 'True', 'abc'], dtype='<U32')

In [104]:
b[0]

'12'

In [107]:
b[:] = 111
b

array(['111', '111', '111', '111', '111'], dtype='<U32')

In [108]:
a

array([23245,    27,   546,   215, -1234])

In [111]:
#we can always make the copy of the array
c = a.copy()
c

array([23245,    27,   546,   215, -1234])